# Generated by Django 5.1 on 2025-02-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydroPowerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('river_flow', models.FloatField()),
                ('budget', models.FloatField()),
                ('power_requirement', models.FloatField()),
                ('civil_design_text', models.TextField(blank=True, null=True)),
                ('civil_design_image', models.URLField(blank=True, null=True)),
                ('hydroelectric_text', models.TextField(blank=True, null=True)),
                ('hydroelectric_image', models.URLField(blank=True, null=True)),
                ('mechanical_text', models.TextField(blank=True, null=True)),
                ('mechanical_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
